### ISSUE TITLE
Comparison against Brython & PyScript?

### ISSUE THREAD

**Issue by plutoniumm** [suren-atoyan/x-python#1]
Hey so its known that between the aforementioned, PyScript intends to completely replace JS whereas Brython is in a crude sense build over JS and I think has more features

What would the recommended use cases for `x-py` be against PyScript & Brython and where does it fit on the spectrum between the two if at all

**Comment by suren-atoyan** [comment]
Hey, @plutoniumm 👋 Thanks for the question.

`Brython`, as you mentioned, is built over JS - in comparison, `PyScript` and `x-python` are based on `pyodide` (which is a real python distribution for the browser based on `WebAssembly`). That fundamentally changes things.

`x-python` is an abstraction over `pyodide` that provides a clean API for code executing, code completion, code formatting, package installation, etc. Both `Brython` and `PyScript` are HTML/script oriented, while `xPython` is primarily for JS developers and for programmatic use. So, instead of doing this:

`Brython` or `PyScript`
```html
<script>
import numpy as np

np.random.rand()
</script>
```

in `xPython` you do this inside your JS code:

```js
import * as xPython from '@x-python/core';

const { result: randomNumber } = await xPython.exec({ code: 'import numpy as np; np.random.rand()' });

// do something with randomNumber
```

====================

I've just setup [github discussion](https://github.com/suren-atoyan/x-python/discussions/2) for `x-python`, let's move such kinds of topics to `discussions`.
